Add LinkedIn multi-page Community Guidelines
OpenTermsArchive/pga-declarations pull request #72
Opened 2022-10-27 13:13 UTC by afisher3578

I am adding the extended Community Guidelines. I did not add the history file entry because I wanted to see how I should proceed with this since the community guidelines were not broken. 

In this situation can I write a history file that overwrites all of the history of the LinkedIn CG to include the multi-page tracking?

2022-10-31 07:49 UTC, MattiSG commented
Hi @afisher3578, thanks for asking this question 🙂 History files are not here because the previous version was broken, but because the source data or the way to handle it has changed in a way that is not compatible with the previous version.

> can I write a history file that overwrites all of the history of the LinkedIn CG to include the multi-page tracking?

This would not make sense, as the source data is not in the snapshots. Yes, the declaration might be valid in the past already, but nobody can know since the source URLs were not tracked: what you see now might have had different URLs last week, so your history file might be wrong. Beyond that uncertainty, the source data is not present, so you would encounter an error when rewriting history. You should thus still add a history entry.

Please let me know if that is not clear 🙂

2022-10-31 07:49 UTC, MattiSG requested changes
Please add a history entry.

2022-11-01 13:20 UTC, martinratinaud commented
Also for this kind of update, I suggest you

- grab a commit of the [latest version](https://github.com/OpenTermsArchive/pga-versions/commit/7dbe4f1c2d5c225c8fe43708a7974e18be923ae0) of the corresponding document
- Paste it in the [contribution tool](https://contribute.opentermsarchive.org/service?&expertMode=true&commit=https%3A%2F%2Fgithub.com%2FOpenTermsArchive%2Fpga-versions%2Fcommit%2F7dbe4f1c2d5c225c8fe43708a7974e18be923ae0)
- Do not change nothing and click on `Send document`

This will create a PR with the history already populated
You can then
- checkout this branch
- modify the `validUntil` to now
- transform the declaration into multipage

2022-11-03 07:42 UTC, afisher3578 commented
Handled with contrib tool in #81

2022-11-03 07:42 UTC, closed without merging